# ui/helpers.py
# -*- coding: utf-8 -*-
import logging
import traceback
import config_manager

def log_error(message: str):
    logging.error(f"{message}\n{traceback.format_exc()}")

TRANSLATIONS = {
    "zh": {
        "api_key": "大模型 API Key:",
        "base_url": "大模型 Base URL:",
        "interface_format": "接口格式:",
        "model_name": "模型名称:",
        "temperature": "创意温度 (Temperature):",
        "max_tokens": "单次最大 Token (Max Tokens):",
        "timeout": "超时时间 (秒):",
        "test_llm": "测试大模型连接",
        
        "emb_api_key": "向量 API Key (可选):",
        "emb_interface": "向量接口格式:",
        "emb_url": "向量 Base URL (可选):",
        "emb_model": "向量模型名称:",
        "emb_k": "召回条数 (Top-K):",
        "test_emb": "测试向量模型连接",
        
        "arch_llm": "生成架构所用大模型",
        "outline_llm": "生成大目录所用大模型",
        "draft_llm": "生成草稿所用大模型",
        "finalize_llm": "定稿章节所用大模型",
        "consistency_llm": "一致性审校所用大模型",
        "final_chapter_llm": "定稿章节所用大模型",
        "consistency_review_llm": "一致性审校所用大模型",
        "save_choose": "保存配置",
        "refresh_choose": "刷新配置",
        
        "proxy_enabled": "启用网络代理:",
        "proxy_address": "代理地址:",
        "proxy_port": "代理端口:",
        "save_proxy": "保存代理设置",
        
        "topic": "故事主题(Topic):",
        "genre": "作品类型(Genre):",
        "num_chapters": "章节总数:",
        "word_number": "单章字数:",
        "filepath": "项目保存路径:",
        "browse": "浏览...",
        "chapter_num": "撰写章节号:",
        "user_guidance": "故事/章节指导:",
        "characters": "本章核心人物:",
        "import": "导入",
        "key_items": "关键道具:",
        "scene": "空间坐标:",
        "time": "时间压力:",

        # Main Tab / Left Area / Buttons
        "chapter_word_label": "章节数 & 每章字数:",
        "num_chapters_sub": "章节数:",
        "word_number_sub": "每章字数:",
        "btn_check_consistency": "一致性审校",
        "btn_import_knowledge": "导入知识库",
        "btn_clear_vectorstore": "清空向量库",
        "plot_arcs_btn": "查看剧情要点",
        "role_library_btn": "角色库",
        "chapter_editable_label": "本章内容（可编辑）  字数: {}",
        "btn_generate_architecture": "Step1. 生成架构",
        "btn_generate_directory": "Step2. 生成目录",
        "btn_generate_chapter": "Step3. 生成草稿",
        "btn_finalize_chapter": "Step4. 定稿章节",
        "btn_batch_generate": "批量生成",
        "log_label": "输出日志 (只读)",

        # Setting Tab
        "load_setting_btn": "加载 Novel_architecture.txt",
        "save_changes": "保存修改",
        "word_count": "字数: {}",
        "warning": "警告",
        "set_path_warning": "请先设置保存文件路径",
        "loaded_setting_log": "已加载 Novel_architecture.txt 内容到编辑区。",
        "saved_setting_log": "已保存对 Novel_architecture.txt 的修改。",

        # Directory Tab
        "load_directory_btn": "加载 Novel_directory.txt",
        "loaded_directory_log": "已加载 Novel_directory.txt 内容到编辑区。",
        "saved_directory_log": "已保存对 Novel_directory.txt 的修改。",

        # Character Tab
        "load_character_btn": "加载 character_state.txt",
        "loaded_character_log": "已加载 character_state.txt 到编辑区。",
        "saved_character_log": "已保存对 character_state.txt 的修改。",

        # Summary Tab
        "load_summary_btn": "加载 global_summary.txt",
        "loaded_summary_log": "已加载 global_summary.txt 到编辑区。",
        "saved_summary_log": "已保存对 global_summary.txt 的修改。",

        # Chapters Tab
        "prev_chapter": "<< 上一章",
        "next_chapter": "下一章 >>",
        "refresh_chapters_btn": "刷新章节列表",
        "no_chapters_dir": "尚未找到 chapters 文件夹，请先生成章节或检查保存路径。",
        "chapter_file_not_found": "章节文件 {} 不存在！",
        "no_chapter_selected": "尚未选择章节，无法保存。",
        "saved_chapter_log": "已保存对第 {} 章的修改。",
        "first_chapter": "已经是第一章了。",
        "last_chapter": "已经是最后一章了。",
        "info": "提示",

        # Config Tab
        "current_config": "当前配置",
        "default_config": "默认配置",
        "btn_add": "➕ 新增",
        "btn_rename": "✏️ 重命名",
        "btn_delete": "🗑️ 删除",
        "btn_save": "💾 保存",
        "error": "错误",
        "new_config_title": "新增配置",
        "new_config_prompt": "请输入新配置名称:",
        "config_exists_err": "配置名称 '{}' 已存在!",
        "new_config_success": "已成功创建新配置: {}",
        "keep_one_config_err": "至少需要保留一个配置!",
        "confirm_delete_title": "确认删除",
        "confirm_delete_prompt": "确定要删除配置 '{}' 吗?\n此操作不可撤销!",
        "delete_success": "已删除配置: {}，并已更新配置文件",
        "save_config_fail": "保存配置文件失败: {}",
        "config_not_found": "未找到选中的配置!",
        "config_not_exist": "配置不存在!",
        "config_save_success": "配置 {} 已保存并持久化到文件",
        "rename_config_title": "重命名配置",
        "rename_config_prompt": "请输入新的配置名称 (原名称: {}):",
        "rename_config_success": "配置已从 '{}' 重命名为 '{}'",
        "load_config_success": "已加载配置。",
        "load_config_fail": "未找到或无法读取配置文件。",
        "save_config_btn_success": "配置已保存至 config.json",
        "save_config_btn_fail": "保存配置失败。",

        # WebDAV Settings
        "webdav_title": "webdav设置",
        "webdav_url": "Webdav URL",
        "webdav_username": "Webdav用户名",
        "webdav_password": "Webdav密码",
        "test_connection": "测试连接",
        "backup": "备份",
        "restore": "恢复",
        "success": "成功",
        "webdav_success": "WebDAV 连接成功！",
        "backup_success": "配置备份成功！",
        "restore_success": "配置恢复成功！",
        "restore_error": "配置恢复失败，未修改本地配置文件。",
        "create_remote_dir_failed": "创建远程备份目录失败",
        "upload_config_failed": "上传配置文件失败",

        # Generation Handlers / Dialogs
        "confirm_title": "确认",
        "gen_arch_confirm": "确定要生成小说架构吗？",
        "gen_arch_start": "开始生成小说架构...",
        "gen_arch_done": "✅ 小说架构生成完成。请在 'Novel Architecture' 标签页查看或编辑。",
        "gen_arch_error": "生成小说架构时出错",
        "gen_dir_confirm": "确定要生成章节目录吗？",
        "gen_dir_start": "开始生成章节目录...",
        "gen_dir_done": "✅ 章节目录生成完成。请在 'Chapter Blueprint' 标签页查看或编辑。",
        "gen_dir_error": "生成章节目录时出错",
        "gen_draft_confirm": "确定要生成第 {} 章的草稿吗？这可能需要几分钟...",
        "gen_draft_start": "开始生成第 {} 章的草稿...",
        "gen_draft_done": "✅ 第 {} 章的草稿生成完成。请在 'Chapters Manage' 标签页查看或编辑。",
        "gen_draft_error": "生成章节草稿时出错",
        "finalize_chapter_confirm": "确定要定稿当前章节吗？",
        "finalize_chapter_enrich_confirm": "本章是否有已生成的草稿？\n\n[是]：将基于现有草稿内容进行扩展润色。\n[否]：直接开始根据大纲和前文全新生成该章节定稿内容。",
        "finalize_chapter_start": "开始为第 {} 章进行定稿创作...",
        "finalize_chapter_done": "✅ 第 {} 章的定稿创作完成。请在 'Chapters Manage' 标签页查看或编辑。",
        "finalize_chapter_error": "定稿章节时出错",
        "clear_vectorstore_warn": "确定要清空本地向量库吗？此操作不可恢复！",
        "clear_vectorstore_warn_2": "你确定真的要删除所有向量数据吗？此操作不可恢复！",
        "clear_vectorstore_done": "向量库清空完成。",
        "clear_vectorstore_error": "清空向量库时出错",
        "no_plot_arcs": "当前还未生成任何剧情要点或冲突记录。",
        "batch_gen_title": "批量生成",
        "batch_gen_prompt": "请输入要生成的章节范围，用半角逗号分隔或连字符，如 '1-5' 或 '1,3,5':",
        "batch_gen_invalid": "请输入有效的章节范围",
        "batch_gen_confirm": "确定要批量生成以下章节的草稿吗？\n章节列表: {}\n此操作可能需要较长时间，请耐心等待！",
        "batch_gen_start": "开始批量生成章节草稿: {}",
        "batch_gen_chapter_start": "--- 开始生成第 {} 章 ({}/{}) ---",
        "batch_gen_chapter_done": "第 {} 章生成成功！",
        "batch_gen_all_done": "✅ 批量生成完成。生成成功的章节: {}",
        "batch_gen_error": "批量生成章节草稿时出错",
        
        "prompt_dialog_title": "当前章节请求提示词（可编辑）",
        "btn_confirm_use": "确认使用",
        "btn_cancel_request": "取消请求",
        "prep_draft_prompt": "生成第 {} 章草稿：准备生成请求提示词...",
        "draft_cancelled_log": "❌ 用户取消了草稿生成请求。",
        "draft_failed_log": "⚠️ 本章草稿生成失败或无内容。",
        
        "wc_low_title": "字数不足",
        "wc_low_prompt": "当前章节字数 ({}) 低于目标字数({})的70%，是否要尝试扩写？",
        "enriching_chapter": "正在扩写章节内容...",
        "consistency_empty_err": "⚠️ 当前章节文件为空或不存在，无法审校。",
        "consistency_start": "开始一致性审校...",
        "consistency_done": "✅ 一致性审校完成。",
        "consistency_error": "进行一致性审校时出错",
        
        "second_confirm": "二次确认",
        "clear_vectorstore_fail": "未能清空向量库，请关闭程序后手动删除 {} 下的 vectorstore 文件夹。",
        "plot_arcs_title": "剧情要点/未解决冲突",
        "no_arcs_recorded": "当前没有记录的剧情要点或冲突。",
        "min_words": "最低字数:",
        "auto_enrich_checkbox": "低于最低字数时自动扩写",
        "fill_all_info": "请填写完整信息。",
        "btn_confirm": "确认",
        "btn_cancel": "取消",
        
        "start_chapter": "起始章节:",
        "end_chapter": "结束章节:",
        "expected_words": "期望字数:"
    },
    "en": {
        "api_key": "API Key:",
        "base_url": "Base URL:",
        "interface_format": "Format:",
        "model_name": "Model Name:",
        "temperature": "Temperature:",
        "max_tokens": "Max Tokens:",
        "timeout": "Timeout (sec):",
        "test_llm": "Test Connection",
        
        "emb_api_key": "Embedding API Key:",
        "emb_interface": "Embedding Format:",
        "emb_url": "Embedding Base URL:",
        "emb_model": "Embedding Model Name:",
        "emb_k": "Retrieval Top-K:",
        "test_emb": "Test Connection",
        
        "arch_llm": "Architecture LLM",
        "outline_llm": "Outline LLM",
        "draft_llm": "Draft LLM",
        "finalize_llm": "Finalize LLM",
        "consistency_llm": "Consistency LLM",
        "final_chapter_llm": "Finalize LLM",
        "consistency_review_llm": "Consistency LLM",
        "save_choose": "Save Config",
        "refresh_choose": "Refresh Configs",
        
        "proxy_enabled": "Enable Proxy:",
        "proxy_address": "Proxy Host:",
        "proxy_port": "Proxy Port:",
        "save_proxy": "Save Proxy",
        
        "topic": "Topic:",
        "genre": "Genre:",
        "num_chapters": "Total Chapters:",
        "word_number": "Words/Chapter:",
        "filepath": "Save Path:",
        "browse": "Browse...",
        "chapter_num": "Chapter No:",
        "user_guidance": "Guidance:",
        "characters": "Characters:",
        "import": "Import",
        "key_items": "Key Items:",
        "scene": "Scene Location:",
        "time": "Time Constraint:",

        # Main Tab / Left Area / Buttons
        "chapter_word_label": "Chapters & Words per Chapter:",
        "num_chapters_sub": "Chapters:",
        "word_number_sub": "Words/Chapter:",
        "btn_check_consistency": "Check Consistency",
        "btn_import_knowledge": "Import Knowledge",
        "btn_clear_vectorstore": "Clear Vectorstore",
        "plot_arcs_btn": "View Plot Arcs",
        "role_library_btn": "Role Library",
        "chapter_editable_label": "Current Chapter (Editable)  Words: {}",
        "btn_generate_architecture": "Step1. Gen Architecture",
        "btn_generate_directory": "Step2. Gen Directory",
        "btn_generate_chapter": "Step3. Gen Draft",
        "btn_finalize_chapter": "Step4. Finalize Chapter",
        "btn_batch_generate": "Batch Generate",
        "log_label": "Output Log (Read Only)",

        # Setting Tab
        "load_setting_btn": "Load Novel_architecture.txt",
        "save_changes": "Save Changes",
        "word_count": "Words: {}",
        "warning": "Warning",
        "set_path_warning": "Please set the save directory first",
        "loaded_setting_log": "Loaded Novel_architecture.txt content to edit area.",
        "saved_setting_log": "Saved changes to Novel_architecture.txt.",

        # Directory Tab
        "load_directory_btn": "Load Novel_directory.txt",
        "loaded_directory_log": "Loaded Novel_directory.txt content to edit area.",
        "saved_directory_log": "Saved changes to Novel_directory.txt.",

        # Character Tab
        "load_character_btn": "Load character_state.txt",
        "loaded_character_log": "Loaded character_state.txt content to edit area.",
        "saved_character_log": "Saved changes to character_state.txt.",

        # Summary Tab
        "load_summary_btn": "Load global_summary.txt",
        "loaded_summary_log": "Loaded global_summary.txt content to edit area.",
        "saved_summary_log": "Saved changes to global_summary.txt.",

        # Chapters Tab
        "prev_chapter": "<< Prev Chapter",
        "next_chapter": "Next Chapter >>",
        "refresh_chapters_btn": "Refresh Chapters List",
        "no_chapters_dir": "Chapters directory not found, please generate chapters or check save path.",
        "chapter_file_not_found": "Chapter file {} does not exist!",
        "no_chapter_selected": "No chapter selected, cannot save.",
        "saved_chapter_log": "Saved changes to Chapter {}.",
        "first_chapter": "This is already the first chapter.",
        "last_chapter": "This is already the last chapter.",
        "info": "Info",

        # Config Tab
        "current_config": "Current Config",
        "default_config": "Default Config",
        "btn_add": "➕ Add",
        "btn_rename": "✏️ Rename",
        "btn_delete": "🗑️ Delete",
        "btn_save": "💾 Save",
        "error": "Error",
        "new_config_title": "Add Config",
        "new_config_prompt": "Please enter the name of the new config:",
        "config_exists_err": "Config name '{}' already exists!",
        "new_config_success": "Successfully created new config: {}",
        "keep_one_config_err": "Must keep at least one config!",
        "confirm_delete_title": "Confirm Delete",
        "confirm_delete_prompt": "Are you sure you want to delete config '{}'?\nThis action cannot be undone!",
        "delete_success": "Deleted config: {}, and updated the config file.",
        "save_config_fail": "Failed to save config file: {}",
        "config_not_found": "Selected config not found!",
        "config_not_exist": "Config does not exist!",
        "config_save_success": "Config {} has been saved and persisted to file.",
        "rename_config_title": "Rename Config",
        "rename_config_prompt": "Please enter the new config name (original: {}):",
        "rename_config_success": "Config renamed from '{}' to '{}'",
        "load_config_success": "Loaded configuration successfully.",
        "load_config_fail": "Configuration file not found or unreadable.",
        "save_config_btn_success": "Configuration saved to config.json",
        "save_config_btn_fail": "Failed to save configuration.",

        # WebDAV Settings
        "webdav_title": "WebDAV Settings",
        "webdav_url": "WebDAV URL",
        "webdav_username": "WebDAV Username",
        "webdav_password": "WebDAV Password",
        "test_connection": "Test Connection",
        "backup": "Backup",
        "restore": "Restore",
        "success": "Success",
        "webdav_success": "WebDAV Connection Successful!",
        "backup_success": "Config Backup Successful!",
        "restore_success": "Config Restore Successful!",
        "restore_error": "Config restore failed, local config file not modified.",
        "create_remote_dir_failed": "Failed to create remote backup directory.",
        "upload_config_failed": "Failed to upload config file.",

        # Generation Handlers / Dialogs
        "confirm_title": "Confirm",
        "gen_arch_confirm": "Are you sure you want to generate the novel architecture?",
        "gen_arch_start": "Starting novel architecture generation...",
        "gen_arch_done": "✅ Novel architecture generated. Check or edit it in 'Novel Architecture' tab.",
        "gen_arch_error": "Error generating novel architecture",
        "gen_dir_confirm": "Are you sure you want to generate the chapter directory?",
        "gen_dir_start": "Starting chapter directory generation...",
        "gen_dir_done": "✅ Chapter directory generated. Check or edit it in 'Chapter Blueprint' tab.",
        "gen_dir_error": "Error generating chapter directory",
        "gen_draft_confirm": "Are you sure you want to generate draft for Chapter {}? This may take several minutes...",
        "gen_draft_start": "Starting draft generation for Chapter {}...",
        "gen_draft_done": "✅ Chapter {} draft generated. Check or edit it in 'Chapters Manage' tab.",
        "gen_draft_error": "Error generating chapter draft",
        "finalize_chapter_confirm": "Are you sure you want to finalize current chapter?",
        "finalize_chapter_enrich_confirm": "Does this chapter have an existing generated draft?\n\n[Yes]: Will expand and polish the existing draft.\n[No]: Will generate a fresh finalized chapter from outline and summary.",
        "finalize_chapter_start": "Starting to finalize Chapter {}...",
        "finalize_chapter_done": "✅ Chapter {} finalized. Check or edit it in 'Chapters Manage' tab.",
        "finalize_chapter_error": "Error finalising chapter",
        "clear_vectorstore_warn": "Are you sure you want to clear local vectorstore? This cannot be undone!",
        "clear_vectorstore_warn_2": "Are you absolutely sure you want to delete all vector data? This cannot be undone!",
        "clear_vectorstore_done": "Vectorstore cleared successfully.",
        "clear_vectorstore_error": "Error clearing vectorstore",
        "no_plot_arcs": "No plot arcs or conflicts have been generated yet.",
        "batch_gen_title": "Batch Generate",
        "batch_gen_prompt": "Please enter chapter ranges to generate (comma-separated or hyphenated, e.g., '1-5' or '1,3,5'):",
        "batch_gen_invalid": "Please enter a valid chapter range",
        "batch_gen_confirm": "Are you sure you want to batch generate drafts for these chapters?\nChapter list: {}\nThis may take a long time!",
        "batch_gen_start": "Starting batch draft generation for chapters: {}",
        "batch_gen_chapter_start": "--- Starting generation of Chapter {} ({}/{}) ---",
        "batch_gen_chapter_done": "Chapter {} generated successfully!",
        "batch_gen_all_done": "✅ Batch generation completed. Successfully generated chapters: {}",
        "batch_gen_error": "Error batch generating chapter drafts",
        
        "prompt_dialog_title": "Current Chapter Prompt (Editable)",
        "btn_confirm_use": "Confirm and Use",
        "btn_cancel_request": "Cancel Request",
        "prep_draft_prompt": "Generating Chapter {} draft: Preparing prompt...",
        "draft_cancelled_log": "❌ User cancelled draft generation request.",
        "draft_failed_log": "⚠️ Current chapter draft generation failed or returned empty.",
        
        "wc_low_title": "Word Count Low",
        "wc_low_prompt": "Current chapter word count ({}) is below 70% of target ({}), would you like to expand it?",
        "enriching_chapter": "Expanding chapter content...",
        "consistency_empty_err": "⚠️ Current chapter file is empty or missing, cannot check consistency.",
        "consistency_start": "Starting consistency review...",
        "consistency_done": "✅ Consistency review completed.",
        "consistency_error": "Error performing consistency review",
        
        "second_confirm": "Second Confirm",
        "clear_vectorstore_fail": "Failed to clear vectorstore, please close the application and manually delete the vectorstore folder under {}.",
        "plot_arcs_title": "Plot Arcs / Unresolved Conflicts",
        "no_arcs_recorded": "No plot arcs or conflicts recorded yet.",
        "min_words": "Minimum Words:",
        "auto_enrich_checkbox": "Auto-expand if below minimum words",
        "fill_all_info": "Please fill in all information.",
        "btn_confirm": "Confirm",
        "btn_cancel": "Cancel",
        
        "start_chapter": "Start Chapter:",
        "end_chapter": "End Chapter:",
        "expected_words": "Expected Words:"
    }
}

def get_text(key: str, fallback: str) -> str:
    lang = "en" if config_manager.IS_ENGLISH else "zh"
    return TRANSLATIONS[lang].get(key, fallback)
